language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo build --release
  - cargo test
  - |
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)

env:
  global:
    - RUST_BACKTRACE=1

before_cache:
  - cargo install cargo-tarpaulin
before_script:
  - rustup component add rustfmt
  - rustup component add clippy

