name: Rust

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: |
        rustup component add rustfmt
        cargo fmt --all -- --check
    - name: Catch common mistakes and improve Rust code
      run: |
        rustup component add clippy
        cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
